# Generated by Django 5.1.3 on 2024-11-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
