# Generated by Django 5.1.3 on 2024-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_admin', '0002_alter_articlemodel_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
