# Generated by Django 5.1.3 on 2024-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_admin', '0005_alter_articlemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
